"""empty message

Revision ID: 4e21cbe0c48e
Revises: bf5a6885a045
Create Date: 2025-07-31 17:03:35.347474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e21cbe0c48e'
down_revision = 'bf5a6885a045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=511), nullable=True))
        batch_op.drop_column('memo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memo', sa.VARCHAR(length=511), nullable=True))
        batch_op.drop_column('note')

    # ### end Alembic commands ###
