"""init

Revision ID: 514948808ee7
Revises: 
Create Date: 2025-07-27 11:52:15.683767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514948808ee7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('img', sa.LargeBinary(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('add_date', sa.DateTime(timezone=255), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=511), nullable=True),
    sa.Column('tag', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('shelves',
    sa.Column('shelf_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.PrimaryKeyConstraint('shelf_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelves')
    op.drop_table('books')
    # ### end Alembic commands ###
