"""Add nullable page_img column to Book

Revision ID: 9ae300baca0e
Revises: b0ab998d4244
Create Date: 2025-08-01 00:31:21.179069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae300baca0e'
down_revision = 'b0ab998d4244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_img', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('page_img')

    # ### end Alembic commands ###
