"""empty message

Revision ID: bf5a6885a045
Revises: 
Create Date: 2025-07-27 13:19:50.642947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5a6885a045'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelves',
    sa.Column('shelf_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('shelf_id')
    )
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('img', sa.LargeBinary(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('add_date', sa.DateTime(timezone=255), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=511), nullable=True),
    sa.Column('tag', sa.String(length=10), nullable=True),
    sa.Column('shelf_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.shelf_id'], name='fk_book_shelf'),
    sa.PrimaryKeyConstraint('book_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('shelves')
    # ### end Alembic commands ###
