"""Add page_img column to Book model

Revision ID: d31a07ef0a8e
Revises: b0ab998d4244
Create Date: 2025-08-01 01:29:57.964186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31a07ef0a8e'
down_revision = 'b0ab998d4244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_img', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('page_img')

    # ### end Alembic commands ###
